; ===========================================================================
; ---------------------------------------------------------------------------
; Object pointers
; ---------------------------------------------------------------------------

Obj_Index:
	dc.l	SonicPlayer		; 01
	dc.l	DeleteObject		; 02
	dc.l	DeleteObject		; 03
	dc.l	DeleteObject		; 04
	dc.l	SpinDust		; 05
	dc.l	AfterImage		; 06
	dc.l	DeleteObject		; 07
	dc.l	Splash			; 08
	dc.l	SonicSpecial		; 09
	dc.l	DrownCount		; 0A
	dc.l	Pole			; 0B
	dc.l	FlapDoor		; 0C
	dc.l	Signpost		; 0D
	dc.l	TitleSonic		; 0E
	dc.l	PSBTM			; 0F
	dc.l	BubbleParticle		; 10
	dc.l	Bridge			; 11
	dc.l	SpinningLight		; 12
	dc.l	LavaMaker		; 13
	dc.l	LavaBall		; 14
	dc.l	SwingingPlatform	; 15
	dc.l	Harpoon			; 16
	dc.l	Helix			; 17
	dc.l	BasicPlatform		; 18
	dc.l	DeleteObject		; 19
	dc.l	CollapseLedge		; 1A
	dc.l	DeleteObject		; 1B
	dc.l	Scenery			; 1C
	dc.l	DeleteObject		; 1D
	dc.l	BallHog			; 1E
	dc.l	Crabmeat		; 1F
	dc.l	Cannonball		; 20
	dc.l	DeleteObject		; 21
	dc.l	BuzzBomber		; 22
	dc.l	Missile			; 23
	dc.l	DeleteObject		; 24
	dc.l	Rings			; 25
	dc.l	Monitor			; 26
	dc.l	ExplosionItem		; 27
	dc.l	Animals			; 28
	dc.l	Points			; 29
	dc.l	AutoDoor		; 2A
	dc.l	Chopper			; 2B
	dc.l	Jaws			; 2C
	dc.l	Burrobot		; 2D
	dc.l	PowerUp			; 2E
	dc.l	LargeGrass		; 2F
	dc.l	GlassBlock		; 30
	dc.l	ChainStomp		; 31
	dc.l	Button			; 32
	dc.l	PushBlock		; 33
	dc.l	TitleCard		; 34
	dc.l	GrassFire		; 35
	dc.l	Spikes			; 36
	dc.l	RingLoss		; 37
	dc.l	ShieldItem		; 38
	dc.l	GameOverCard		; 39
	dc.l	GotThroughCard		; 3A
	dc.l	PurpleRock		; 3B
	dc.l	SmashWall		; 3C
	dc.l	BossGreenHill		; 3D
	dc.l	Prison			; 3E
	dc.l	Explosion		; 3F
	dc.l	MotoBug			; 40
	dc.l	Springs			; 41
	dc.l	Newtron			; 42
	dc.l	Roller			; 43
	dc.l	EdgeWalls		; 44
	dc.l	DeleteObject		; 45
	dc.l	MarbleBrick		; 46
	dc.l	Bumper			; 47
	dc.l	BossBall		; 48
	dc.l	WaterSound		; 49
	dc.l	DeleteObject		; 4A
	dc.l	GiantRing		; 4B
	dc.l	GeyserMaker		; 4C
	dc.l	LavaGeyser		; 4D
	dc.l	LavaWall		; 4E
	dc.l	DeleteObject		; 4F
	dc.l	Yadrin			; 50
	dc.l	SmashBlock		; 51
	dc.l	MovingBlock		; 52
	dc.l	CollapseFloor		; 53
	dc.l	LavaTag			; 54
	dc.l	Basaran			; 55
	dc.l	FloatingBlock		; 56
	dc.l	SpikeBall		; 57
	dc.l	BigSpikeBall		; 58
	dc.l	Elevator		; 59
	dc.l	CirclingPlatform	; 5A
	dc.l	Staircase		; 5B
	dc.l	Pylon			; 5C
	dc.l	Fan			; 5D
	dc.l	Seesaw			; 5E
	dc.l	Bomb			; 5F
	dc.l	Orbinaut		; 60
	dc.l	LabyrinthBlock		; 61
	dc.l	Gargoyle		; 62
	dc.l	LabyrinthConvey		; 63
	dc.l	Bubble			; 64
	dc.l	Waterfall		; 65
	dc.l	Junction		; 66
	dc.l	RunningDisc		; 67
	dc.l	Conveyor		; 68
	dc.l	SpinPlatform		; 69
	dc.l	Saws			; 6A
	dc.l	ScrapStomp		; 6B
	dc.l	VanishPlatform		; 6C
	dc.l	Flamethrower		; 6D
	dc.l	Electro			; 6E
	dc.l	SpinConvey		; 6F
	dc.l	Girder			; 70
	dc.l	Invisibarrier		; 71
	dc.l	Teleport		; 72
	dc.l	BossMarble		; 73
	dc.l	BossFire		; 74
	dc.l	BossSpringYard		; 75
	dc.l	BossBlock		; 76
	dc.l	BossLabyrinth		; 77
	dc.l	Caterkiller		; 78
	dc.l	Lamppost		; 79
	dc.l	BossStarLight		; 7A
	dc.l	BossSpikeball		; 7B
	dc.l	RingFlash		; 7C
	dc.l	HiddenBonus		; 7D
	dc.l	SSResult		; 7E
	dc.l	SSRChaos		; 7F
	dc.l	ContScrItem		; 80
	dc.l	ContSonic		; 81
	dc.l	ScrapEggman		; 82
	dc.l	FalseFloor		; 83
	dc.l	EggmanCylinder		; 84
	dc.l	BossFinal		; 85
	dc.l	BossPlasma		; 86
	dc.l	EndSonic		; 87
	dc.l	EndChaos		; 88
	dc.l	EndSTH			; 89
	dc.l	CreditsText		; 8A
	dc.l	EndEggman		; 8B
	dc.l	TryChaos		; 8C

; ---------------------------------------------------------------------------
